kind: Service
apiVersion: v1
metadata:
  name: springboot-k8s-acnt-mysql # name of the service
  labels:
    name: springboot-k8s-acnt-mysql
spec:
  ports:
    - nodePort: 30161 # port number
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:           
    app: springboot-k8s-acnt-mysql # name of the deployment
  type: NodePort       

---
# Define a 'Persistent Voulume Claim'(PVC) for Mysql Storage, dynamically provisioned by cluster
apiVersion: v1
kind: PersistentVolumeClaim # type of the object
metadata:
  name: myacnt-pv-claim # name of PVC essential for identifying the storage data
  labels:
    app: springboot-k8s-acnt-mysql
    tier: application
spec:
  accessModes:
    - ReadWriteOnce   #This specifies the mode of the claim that we are trying to create.
  resources:
    requests:
      storage: 1Gi    #This will tell kubernetes about the amount of space we are trying to claim.
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: springboot-k8s-acnt-mysql
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: springboot-k8s-acnt-mysql
  template: 
    metadata: 
      labels: 
        app: springboot-k8s-acnt-mysql
    spec: 
      containers: 
        - 
          env: 
            - 
              name: DB_HOST
              valueFrom: 
                configMapKeyRef: 
                  key: host
                  name: db-conf
            - 
              name: DB_NAME
              valueFrom: 
                configMapKeyRef: 
                  key: name
                  name: db-conf
            - 
              name: DB_USERNAME
              valueFrom: 
                secretKeyRef: 
                  key: username
                  name: db-credentials
            - 
              name: DB_PASSWORD
              valueFrom: 
                secretKeyRef: 
                  key: password
                  name: db-credentials
              volumeMounts: 
                - 
                  mountPath: /usr/local/acnt/data
                  name: myacnt-pv-claim
          image: "thulasi29ndocker/account-service:2.0"
          limits: 
            cpu: 500m
            requests: 
              cpu: 200m
          name: springboot-k8s-acnt-mysql
          ports: 
            - 
              containerPort: 8080
          volumes: 
            - 
              name: myacnt-pv-claim
              persistentVolumeClaim: 
                claimName: myacnt-pv-claim



